### ISSUE TITLE
some trouble in building docker image

### ISSUE THREAD

**Issue by LessterWong** [island255/TOSEM2022#1]
I'm trying to build the docker image and then get some trouble. Could you please give me a solution? Thanks a lot

I copy "dockerfile_source2binary" to my Desktop and rename it as "Dockerfile"
command: sudo docker build -t inlinetest:v1 /home/username/Desktop
message:
Collecting lit
  Downloading https://files.pythonhosted.org/packages/91/b7/ebcc3f2008112b72e7686297abcd0014706a3437bfde8bf46fc598ad9d54/lit-15.0.0.post0.tar.gz (131kB)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    ModuleNotFoundError: No module named 'setuptools'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-dcpof7pz/lit/
The command '/bin/sh -c apt-get update &&     apt-get -y --no-install-recommends install         clang-${LLVM_VERSION}         llvm-${LLVM_VERSION}         llvm-${LLVM_VERSION}-dev         llvm-${LLVM_VERSION}-runtime         llvm         libcap-dev         git         subversion         cmake         make         libboost-program-options-dev         python3         python3-dev         python3-pip         perl         flex         bison         libncurses-dev         zlib1g-dev         patch         wget         unzip         libedit-dev         binutils &&     pip3 install -U lit tabulate &&     update-alternatives --install /usr/bin/python python /usr/bin/python3 50' returned a non-zero code: 1

**Comment by island255** [comment]
Installing _python3-setuptools_ will solve it. I have updated the file "dockerfile_source2binary" and you can try it.

**Comment by LessterWong** [comment]
> 

It works! Thanks a lot :)

**Comment by LessterWong** [comment]
> Installing _python3-setuptools_ will solve it. I have updated the file "dockerfile_source2binary" and you can try it.

I'm so sorry that another problem has arisen. 
Step 34/43 : COPY generateshfors2ir.py /home/llvm-coreutils/
COPY failed: file not found in build context or excluded by .dockerignore: stat generateshfors2ir.py: file does not exist

Could you please fix this problem? Sorry for bother you again.

**Comment by island255** [comment]
generateshfors2ir.py is actually not used in the construction of the dataset. I remove this file and subsequent instructions. Now running the docker file should directly produce the corresponding binaries.

**Comment by LessterWong** [comment]
> generateshfors2ir.py is actually not used in the construction of the dataset. I remove this file and subsequent instructions. Now running the docker file should directly produce the corresponding binaries.

I get it :) Thanks again and have a nice day~
